-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stores" add column "is_record_attendance" boolean
--  not null default 'false';
